### PR TITLE
Junit test and additional data for creating necessary foot-encoded graph

### PR DESCRIPTION
**Pull request by chrissssss**
JUnit test with data for small foot-encoded graph and testcase. Easy to see the problem with missing upper loop

### CODE REVIEW

**Comment by karussell** [comment]
Thanks, I'll have a look!

**Comment by karussell** [comment]
Would you add the file GraphhopperBerlin(loop)Dgz-ring.gpx ?

**Comment by chrissssss** [comment]
My bad - I'm REALLY REALLY sorry.
Does the gpsies-link now work? I've changed visibility to public.
I've just seen that I forgot to commit that file :/


2015-02-12 9:27 GMT+01:00 Peter <notifications@github.com>:

**Comment by karussell** [comment]
No problem and yes, download works now - thanks!

**Comment by karussell** [comment]
Please see [my comment](https://github.com/graphhopper/map-matching/issues/1#issuecomment-74108881) where I describe the workarounds. Closing for now.

**Pull request closed without merging**
