### PR TITLE
Add docker

### PR DESCRIPTION
**Pull request by 1kastner**
With docker the server can quickly be started without the need of having a java development environment on the computer. Is related to the idea #121 and the use case #120.

### CODE REVIEW

**Comment by michaz** [comment]
I don't use Docker myself, so I can only evaluate this by pattern-matching and googling.

The Dockerfile seems to be unsimilar to the Dockerfile of e.g. graphhopper itself, and also to be unusual for a Java project -- it inherits from a specific Linux distribution and installs the JDK manually. My knowledge is limited, but this doesn't seem to be what one would usually do.

Looking at the ticket you're referencing, this seems to be about at rather specific use case, so I'm not sure this is general enough to merge it.

**Comment by 1kastner** [comment]
Ok, I might have a look at using java as the base image.
My use case is rather general - just start map-matching in a docker-container.
This way you don't install the dependencies on your own machine but have it bundled somewhere else.

**Comment by 1kastner** [comment]
Btw. thank you for your feedback 👍

**Comment by 1kastner** [comment]
Another option is to have the docker containers generated automatically, see e.g. https://hub.docker.com/r/murphdasurf/map-matching/

**Comment by 1kastner** [comment]
Some reasoning for why a file is placed at which place, why it can be useful etc. can be found here: https://github.com/graphhopper/graphhopper/pull/849.
The commands can be used in pretty much the same way adjusted for this project.

**Comment by 1kastner** [comment]
So many changes this PR would introduce... Seems like I messed something up, I will check it somewhen later

**Comment by 1kastner** [comment]
I checked that if I opened a fresh new pull request with the same changes, the commits and 'foreign' changes would not be shown. Should I do this?

**Comment by raveenb** [comment]
any update when this PR will be merged? a docker based system will be super useful

**Comment by michaz** [comment]
I stand with my comment -- there is nothing special about this project that would require a special dockerfile to go with it. It is a normal Java program that is configured by a configuration file and command line parameters. I think whoever uses Docker would know, or could easily find out, how to run this program with it.

**Pull request closed without merging**
