### PR TITLE
Upate GH Version to Latest Master

### PR DESCRIPTION
**Pull request by boldtrn**
This is just a minor version bump.

### CODE REVIEW

**Comment by easbar** [comment]
Can't you use the `recent_core` branch? And if we update master should we not rather merge `recent_core` into master?

**Comment by boldtrn** [comment]
Oh sorry, I thought with https://github.com/graphhopper/map-matching/commit/996130db056f522e96daaef1c6e702de0753d105 we would be working on master :). In this case, recent_core is definitely better.

**Comment by boldtrn** [comment]
BTW: should we set recent_core as default branch or mention this in the readme or something like that?

**Comment by boldtrn** [comment]
Using recent_core just seems to be a bit inconsistent and I find my self stumbling over every time I do something with map-matching, which is infrequent.

**Pull request closed without merging**
